#!/usr/bin/env python3
"""Generate docs/RELEASE_NOTES.md — a machine-generated release snapshot.

docs/RELEASE.md asks maintainers to hand-assemble catalog stats, eval counts,
and quality-gate results at release time. This generator replaces that manual
step: it derives every number from the committed metadata (catalog, provenance,
eval-harness scenarios, benchmark tasks, tools catalog, rigor coverage), so the
snapshot is reproducible from a checkout and can never drift from the artifacts
it describes. Maintainers paste the snapshot into the GitHub release and add a
hand-written Highlights section on top.

Zero third-party dependencies (TOML via scripts/toml_compat.py). Mirrors the
build-*/--check pattern of the other generators.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import toml_compat

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "eval-harness" / "lib"))
from checks import AUTO_CHECKS  # noqa: E402


def _load_coverage_map():
    """The coverage map owns the method-family roster (METHOD_ORDER); reuse it
    so the snapshot and badge can never disagree with docs/RIGOR_COVERAGE.md."""
    path = ROOT / "scripts" / "build-coverage-map.py"
    spec = importlib.util.spec_from_file_location("aers_build_coverage_map", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


COVERAGE_MAP = _load_coverage_map()
CATALOG = ROOT / "catalog" / "skills.json"
PROVENANCE = ROOT / "catalog" / "provenance.json"
ENRICHED = ROOT / "catalog" / "skills-enriched.json"
TOOLS = ROOT / "tools" / "tools.json"
SCENARIO_DIR = ROOT / "eval-harness" / "scenarios"
TASK_DIR = ROOT / "benchmark" / "tasks"
OUT = ROOT / "docs" / "RELEASE_NOTES.md"
BADGE_OUT = ROOT / "docs" / "badges" / "rigor-coverage.json"


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def scenario_stats() -> dict:
    n_scenarios = 0
    n_rubric = 0
    n_auto = 0
    categories: dict[str, int] = {}
    for path in sorted(SCENARIO_DIR.glob("*.toml")):
        with path.open("rb") as fh:
            s = toml_compat.load(fh)
        n_scenarios += 1
        categories[s.get("category", "?")] = categories.get(s.get("category", "?"), 0) + 1
        for item in s.get("rubric", []):
            n_rubric += 1
            if item.get("check") in AUTO_CHECKS:
                n_auto += 1
    return {
        "scenarios": n_scenarios,
        "rubric_items": n_rubric,
        "auto_checks": n_auto,
        "categories": categories,
    }


def benchmark_stats() -> dict:
    n_tasks = 0
    n_gold = 0
    n_required = 0
    for path in sorted(TASK_DIR.glob("*.toml")):
        with path.open("rb") as fh:
            t = toml_compat.load(fh)
        n_tasks += 1
        for g in t.get("gold", []):
            n_gold += 1
            if g.get("required"):
                n_required += 1
    return {"tasks": n_tasks, "gold_checks": n_gold, "required_checks": n_required}


def build() -> str:
    catalog = load_json(CATALOG)
    provenance = load_json(PROVENANCE)
    enriched = load_json(ENRICHED)
    tools = load_json(TOOLS)
    scen = scenario_stats()
    bench = benchmark_stats()

    summary = catalog.get("summary", {})
    methods = enriched.get("taxonomy", {}).get("method", {})
    licenses = provenance.get("summary", {}).get("licenses", {})

    lines = [
        "# Release Snapshot",
        "",
        "Generated by `scripts/build-release-notes.py` from committed metadata; do not edit by hand.",
        "Regenerate with `make catalog`. Freshness is enforced by `make validate`.",
        "",
        "Paste this snapshot into the GitHub release body and add a hand-written",
        "**Highlights** section on top (see [`RELEASE.md`](RELEASE.md)).",
        "",
        "## Catalog",
        "",
        f"- Top-level collections: **{summary.get('top_level_collections', '?')}**",
        f"- `SKILL.md` files: **{summary.get('skill_files', '?')}**",
        f"- Cataloged agent tools: **{len(tools.get('tools', []))}** ([`tools/CATALOG.md`](../tools/CATALOG.md))",
        "",
        "## Methodological rigor",
        "",
        f"- Method families in the coverage map: **{len(COVERAGE_MAP.METHOD_ORDER)}** ([`RIGOR_COVERAGE.md`](RIGOR_COVERAGE.md))",
        f"- Eval scenarios: **{scen['scenarios']}** "
        f"({scen['rubric_items']} rubric items, {scen['auto_checks']} auto-checkable) "
        "([`../eval-harness/`](../eval-harness/README.md))",
        f"- Benchmark tasks: **{bench['tasks']}** "
        f"({bench['gold_checks']} gold checks, {bench['required_checks']} required) "
        "([`../benchmark/`](../benchmark/README.md))",
        "",
        "### Method families (skills tagged)",
        "",
    ]
    for tag in sorted(methods, key=lambda k: (-methods[k], k)):
        lines.append(f"- `{tag}`: {methods[tag]}")
    lines += [
        "",
        "### Eval scenarios by category",
        "",
    ]
    for cat in sorted(scen["categories"]):
        lines.append(f"- `{cat}`: {scen['categories'][cat]}")
    lines += [
        "",
        "## License buckets",
        "",
    ]
    for name in sorted(licenses):
        lines.append(f"- {name}: {licenses[name]}")
    lines += [
        "",
        "## Quality gates",
        "",
        "- `make check` — catalog/provenance/audit/eval freshness, repo hygiene,",
        "  Paper-WorkFlow gates, stdlib unit tests, eval-harness lint + graded smoke,",
        "  and the strict numeric benchmark (reference-gold drift fails the build).",
        "- External links and OpenSSF Scorecard run on their scheduled workflows.",
        "",
    ]
    return "\n".join(lines)


def build_badge() -> str:
    """Shields.io endpoint JSON summarizing the rigor surface (README badge)."""
    scen = scenario_stats()
    bench = benchmark_stats()
    payload = {
        "schemaVersion": 1,
        "label": "rigor",
        "message": (
            f"{len(COVERAGE_MAP.METHOD_ORDER)} method families · "
            f"{bench['tasks']} benchmarks · {scen['scenarios']} evals"
        ),
        "color": "brightgreen",
    }
    return json.dumps(payload, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed snapshot without rewriting it",
    )
    args = parser.parse_args(argv)

    content = build()
    badge = build_badge()
    if args.check:
        stale = []
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            stale.append("docs/RELEASE_NOTES.md")
        if not BADGE_OUT.exists() or BADGE_OUT.read_text(encoding="utf-8") != badge:
            stale.append("docs/badges/rigor-coverage.json")
        if stale:
            print(f"{' and '.join(stale)} stale. Regenerate with:", file=sys.stderr)
            print("  python3 scripts/build-release-notes.py", file=sys.stderr)
            return 1
        print("docs/RELEASE_NOTES.md and rigor badge are current.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    BADGE_OUT.parent.mkdir(parents=True, exist_ok=True)
    BADGE_OUT.write_text(badge, encoding="utf-8")
    print(f"Wrote {BADGE_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
